name: Github actions Demo
on: workflow_dispatch
jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${TEST_SECRET}
        env: 
          TEST_SECRET: ${{ secrets.TEST_SECRET }}