name: Github actions Demo
on: workflow_dispatch
jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: cmd
        env: 
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: echo $TEST_SECRET